### ISSUE TITLE
initial construce from claude(log)

### ISSUE THREAD

**Issue by kitsystemyou** [kitsystemyou/iriam-rag#1]
(claude

---
クローリングとベクトルデータベース構築をAPIとは別のジョブとして切り離す構成に基づいて、より適切な工程を洗い出します。

## 改訂版の分離作業工程

1. **アーキテクチャの設計**
   - 3層構造の設計:
     - バックグラウンドジョブサーバー: クローリングとインデックス構築
     - API層: 質問応答とジョブ管理
     - クライアント: ユーザーインターフェース

2. **バックグラウンドジョブシステムの設計**
   - ジョブ管理システムの選定（Celery、RQなど）
   - ジョブキュー/ブローカーの選定（Redis、RabbitMQなど）
   - ジョブの定義:
     - クローリングジョブ
     - インデックス構築ジョブ
   - ジョブ状態管理の設計
   - 耐障害性と再開機能の設計

3. **共有ストレージの設計**
   - クロールデータの保存方法
   - ベクトルインデックスの保存場所
   - 各コンポーネント間のデータ共有方法

4. **APIレイヤーの設計**
   - エンドポイント設計:
     - `/jobs/crawl` - クローリングジョブの作成
     - `/jobs/{job_id}` - ジョブ状態の確認
     - `/jobs/{job_id}/cancel` - ジョブのキャンセル
     - `/answer` - 質問応答
     - `/indices` - 利用可能なインデックス一覧
   - ジョブ管理APIの設計
   - 質問応答APIの設計

5. **バックグラウンドジョブサーバーの実装**
   - ジョブワーカーの実装
     - PlaywrightCrawlerジョブの実装
     - DocumentProcessorジョブの実装
   - 進捗報告機能の実装
   - エラーハンドリングと再試行機能
   - リソース制限と調整機能

6. **APIサーバーの実装**
   - Webフレームワークのセットアップ
   - ジョブ管理エンドポイントの実装
   - 質問応答エンドポイントの実装
   - RAGSystemクラスの統合
   - 認証とアクセス制御の実装

7. **クライアントの実装**
   - ユーザーインターフェースの設計
   - API連携機能の実装
   - ジョブ制御UI（クローリング開始、状態確認、停止）
   - 質問入力と回答表示UI
   - エラー処理とユーザーフィードバック

8. **データ連携の実装**
   - 共有ストレージへのアクセス機能
   - ジョブ結果の保存と取得
   - ベクトルストアのロードと操作

9. **環境構成の設計**
   - 各コンポーネントの実行環境設計
   - 環境変数管理
   - リソース必要量の見積もり
   - スケーリング戦略

10. **監視と運用機能の実装**
    - ジョブ実行ログの収集
    - パフォーマンスメトリクスの収集
    - アラート設定
    - 定期的なメンテナンス機能

11. **テスト戦略の実装**
    - 各コンポーネントの単体テスト
    - コンポーネント間の統合テスト
    - エンドツーエンドテスト
    - 負荷テスト

12. **デプロイ準備**
    - Dockerイメージ作成
    - コンポーネント間の通信設定
    - 外部サービス接続設定
    - セキュリティ設定

この構成により、リソース集約的なクローリングやインデックス構築処理を独立したバックグラウンドジョブとして実行でき、APIサーバーはより軽量で応答性の高いサービスとして機能します。また、ジョブの状態管理により、長時間実行される処理の進捗を適切にユーザーに伝えることが可能になります。

**Comment by kitsystemyou** [comment]
色々修正後

---
GitHub Actions をバックグラウンドジョブの実行環境として活用する方針に基づいて、工程を再調整します。

## 修正版の分離作業工程

1. **アーキテクチャの設計**
   - 2層構造の設計:
     - API層: 質問応答機能
     - クライアント: ユーザーインターフェース
   - GitHub Actionsによるバッチ処理:
     - クローリングワークフロー
     - ベクトルインデックス構築ワークフロー

2. **GitHub Actionsワークフローの設計**
   - クローリングワークフローの設計:
     - トリガー条件（手動/スケジュール）
     - 実行環境とリソース設定
     - PlaywrightCrawlerの実行
     - 結果の保存
   - インデックス構築ワークフローの設計:
     - トリガー条件（クローリング完了後/手動）
     - DocumentProcessorの実行
     - ベクトルストアの生成と保存

3. **共有ストレージの設計**
   - クロールデータの保存場所（S3/GCS等）
   - ベクトルインデックスの保存場所
   - API層からのアクセス方法

4. **APIレイヤーの設計**
   - エンドポイント設計:
     - `/answer` - 質問応答処理
     - `/indices` - 利用可能なインデックス一覧
     - `/health` - ヘルスチェック
   - 認証メカニズムの設計
   - エラーレスポンスの設計

5. **GitHub Actionsワークフローの実装**
   - `crawl.yml` ワークフローファイルの作成:
     - PlaywrightCrawlerの設定
     - 環境変数の設定
     - 出力データの保存処理
   - `build-index.yml` ワークフローファイルの作成:
     - DocumentProcessorの設定
     - 埋め込み生成とインデックス構築
     - ベクトルストアの保存

6. **APIサーバーの実装**
   - Webフレームワークのセットアップ（FastAPIなど）
   - ベクトルストアのロード機能実装
   - 質問応答エンドポイントの実装
   - RAGSystemクラスの統合
   - エラーハンドリングの強化

7. **クライアントの実装**
   - ユーザーインターフェースの設計
   - 質問入力と回答表示UI
   - APIへのリクエスト機能実装
   - 回答の表示とソース情報の提示
   - エラー処理とユーザーフィードバック

8. **ストレージ連携の実装**
   - API層からストレージへのアクセス機能実装
   - 適切なベクトルストアの選択とロード
   - キャッシュ機能（オプション）

9. **環境変数と設定管理**
   - GitHub Secrets/Variables設定
   - API環境変数設定
   - OpenAI APIキー管理
   - ストレージアクセス認証情報管理

10. **テスト戦略の実装**
    - GitHub Actionsワークフローのテスト
    - APIエンドポイントのテスト
    - クライアント機能のテスト
    - エンドツーエンドテスト

11. **デプロイ準備**
    - APIサーバーのコンテナ化
    - クライアントのビルドとデプロイ設定
    - 必要なインフラリソースの準備
    - 環境ごとの設定分離

12. **ドキュメント作成**
    - GitHub Actionsワークフローの実行方法
    - API仕様書
    - クライアントの使用方法
    - トラブルシューティングガイド

この構成では、リソース集約的なクローリングとインデックス構築処理をGitHub Actionsで定期的または手動で実行し、その結果を共有ストレージに保存します。APIサーバーはこれらの処理結果を読み込んで質問応答機能を提供します。これにより、APIサーバー自体は軽量に保ち、スケーラブルな構成を実現できます。

**Comment by kitsystemyou** [comment]
実装もさせてみる

---

GitHub Actionsを使用して、クローリングとベクトルインデックス構築を行うワークフローの実装計画を以下に示します。リポジトリ内にCSVファイルとしてクロールデータを保存する前提で進めます。

## 1. GitHub Actionsワークフローの実装計画

### A. クローリングワークフロー (`crawl.yml`)

```yaml
name: Crawl Website

on:
  workflow_dispatch:  # 手動実行
    inputs:
      base_url:
        description: 'クローリング対象のベースURL'
        required: true
        default: 'https://support.iriam.com/hc/ja'
      max_pages:
        description: 'クローリングする最大ページ数'
        required: true
        default: '100'
  schedule:
    - cron: '0 0 * * 0'  # 毎週日曜日に実行

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run crawler script
        run: python scripts/crawler.py --base_url ${{ github.event.inputs.base_url || 'https://support.iriam.com/hc/ja' }} --max_pages ${{ github.event.inputs.max_pages || '100' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and push crawled data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/crawled_data.csv
          git commit -m "Update crawled data [skip ci]" || echo "No changes to commit"
          git push
```

### B. インデックス構築ワークフロー (`build-index.yml`)

```yaml
name: Build Vector Index

on:
  workflow_dispatch:  # 手動実行
  workflow_run:
    workflows: ["Crawl Website"]
    types:
      - completed

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build vector index
        run: python scripts/build_index.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and push built index
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/faiss_index/
          git commit -m "Update vector index [skip ci]" || echo "No changes to commit"
          git push
```

### C. スクリプトの分割

元のコードを以下のように分割する必要があります：

1. **`scripts/crawler.py`** - クローリング処理のみを行うスクリプト
2. **`scripts/build_index.py`** - クロールデータからベクトルインデックスを構築するスクリプト
3. **`scripts/api.py`** - APIサーバーの実装

### D. ディレクトリ構造

```
repo/
├── .github/
│   └── workflows/
│       ├── crawl.yml
│       └── build-index.yml
├── scripts/
│   ├── crawler.py
│   ├── build_index.py
│   └── api.py
├── data/
│   ├── crawled_data.csv
│   └── faiss_index/
├── client/
│   └── ... (クライアントアプリケーションのコード)
├── requirements.txt
└── README.md
```

### E. `crawler.py` の要点

- 元のコードから `PlaywrightCrawler` クラスを抽出
- コマンドライン引数のサポート（base_url, max_pages）
- CSVファイルへの保存機能
- ログ出力

```python
# scripts/crawler.py (概略)
import os
import asyncio
import argparse
import pandas as pd
from playwright_crawler import PlaywrightCrawler  # 元コードからクラスを抽出

async def main():
    parser = argparse.ArgumentParser(description='Crawl website')
    parser.add_argument('--base_url', default='https://support.iriam.com/hc/ja')
    parser.add_argument('--max_pages', type=int, default=100)
    args = parser.parse_args()
    
    # クローリング実行
    crawler = PlaywrightCrawler(base_url=args.base_url, max_pages=args.max_pages)
    crawled_data = await crawler.crawl()
    
    # データ保存
    os.makedirs('data', exist_ok=True)
    df = pd.DataFrame(crawled_data)
    df.to_csv("data/crawled_data.csv", index=False)
    print(f"クロール済みデータを保存しました。{len(crawled_data)}件のドキュメントを取得。")

if __name__ == "__main__":
    asyncio.run(main())
```

### F. `build_index.py` の要点

- 元のコードから `DocumentProcessor` クラスを抽出
- CSVファイルからのデータ読み込み
- ベクトルインデックスの構築と保存

```python
# scripts/build_index.py (概略)
import os
import pandas as pd
from document_processor import DocumentProcessor
from langchain_openai import OpenAIEmbeddings

def main():
    # クロールデータの読み込み
    df = pd.read_csv("data/crawled_data.csv")
    crawled_data = df.to_dict('records')
    
    # テキスト処理とベクトル化
    processor = DocumentProcessor(chunk_size=1000, chunk_overlap=200)
    processed_docs = processor.process_documents(crawled_data)
    vector_store = processor.create_vector_index(processed_docs)
    
    # インデックスの保存
    os.makedirs('data/faiss_index', exist_ok=True)
    vector_store.save_local("data/faiss_index")
    print("ベクトルインデックスを保存しました。")

if __name__ == "__main__":
    main()
```

### G. 必要な依存関係 (`requirements.txt`)

```
pandas
numpy
beautifulsoup4
playwright
langchain-openai
langchain
langchain-community
faiss-cpu
openai
fastapi
uvicorn
```

このワークフロー設計により、GitHub Actionsでクローリングとインデックス構築を定期的または手動で実行し、結果をリポジトリ内に保存します。APIサーバーはこれらの保存されたデータを使用して質問応答機能を提供します。

---

ひとまずスクリプト分割してみたのを動かしてみる
